# Generated by Django 4.0 on 2022-07-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallery_reviewrating_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=255, null=True),
        ),
    ]
