# Generated by Django 4.0 on 2022-07-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_doors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeoption', models.CharField(choices=[('0', 'xxl'), ('1', 'lg'), ('2', 'sm'), ('3', 'xsm'), ('4', 'xlg')], max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='variation',
            name='doors',
        ),
        migrations.AddField(
            model_name='variation',
            name='sizeoption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizeoption'),
        ),
    ]
