# Generated by Django 4.0 on 2022-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sizeoption_remove_variation_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeoption',
            name='sizeoption',
            field=models.CharField(choices=[('XL', 'XL'), ('SM', 'SM'), ('LG', 'LG'), ('XXL', 'XXL')], max_length=255, null=True),
        ),
    ]
