# Generated by Django 4.0 on 2022-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_sizeoption_sizeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeoption',
            name='sizeoption',
            field=models.CharField(choices=[('XL', 'XL'), ('SM', 'SM'), ('LG', 'LG'), ('XXL', 'XXL')], max_length=55, null=True),
        ),
    ]
